leaguepredict/leaguepredict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('match_prediction.urls')),
    path('admin/', admin.site.urls),
]

leaguepredict/match_prediction/urls.py
from django.urls import path
from . import views

app_name = 'match_prediction'
urlpatterns = [
    path('', views.index, name='index'),
]

leaguepredict/matchup_prediction/models.py
from django.db import models

# Create your models here.

leaguepredict/match_prediction/forms.py
from django import forms


class SummonerNameForm(forms.Form):
    summoner_name = forms.CharField(label="Your Summoner Name", max_length=100)

leaguepredict/match_prediction/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .util import get_participants, get_summoner_id


from .forms import SummonerNameForm


# Create your views here.
def index(request):
    submitted = False
    if request.method == 'POST':
        form = SummonerNameForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            sname = cd['summoner_name']
            return display(request, sname)
    else:
        form = SummonerNameForm()
        if 'submitted' in request.GET:
            submitted = True
        return render(request, "match_prediction/index.html", {'form': form, 'submitted': submitted})


def display(request, sname):
    participants = get_participants(sname)
    return render(request, "match_prediction/display.html", {'participants': participants})

leaguepredict/matchup_prediction/views.py
from django.shortcuts import render

# Create your views here.

leaguepredict/match_prediction/templates/match_prediction/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for p in participants %}
            <li>
                {{p}}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

leaguepredict/match_prediction/templates/match_prediction/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>League Predict</title>
</head>
<body>
    <form action="{% url 'match_prediction:index' %}" method="post" novalidate>
        {{form}}
        <input type="submit" value="Submit">
        {% csrf_token %}
    </form>
</body>
</html>